spring.application.name=TalentMatchingBE

# THÔNG TIN K?T N?I DATABASE

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# C?U HÌNH HIBERNATE (JPA)
# B?t tính n?ng in câu l?nh SQL ra console ?? d? debug
spring.jpa.show-sql=true
# Format câu l?nh SQL cho d? nhìn
spring.jpa.properties.hibernate.format_sql=true

# Quan tr?ng: C?u hình t? ??ng c?p nh?t b?ng
# 'update': T? ??ng t?o b?ng n?u ch?a có, ho?c thêm c?t m?i n?u code thay ??i
spring.jpa.hibernate.ddl-auto=update

# Khai báo dialect ?? Hibernate bi?t ?ang dùng MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# C?u hình OAuth2 cho Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
# URL ?? Backend nh?y v? Frontend sau khi login thành công
app.oauth2.redirect-uri=http://localhost:3000/oauth2/redirect