spring.application.name=TalentMatchingBE

# --- DATABASE CONFIGURATION ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- OAUTH2 GOOGLE ---
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# --- OAUTH2 FACEBOOK ---
spring.security.oauth2.client.registration.facebook.client-id=${FB_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FB_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=public_profile,email
# Required for Facebook redirect flow
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/facebook
spring.security.oauth2.client.provider.facebook.user-name-attribute=id


# --- CUSTOM APP PROPERTIES ---
app.oauth2.redirect-uri=${APP_OAUTH2_REDIRECT_URI:http://localhost:8080/swagger-ui/index.html}
app.jwt.secret=${JWT_SECRET}

# --- SWAGGER / SPRINGDOC ---
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.use-root-path=true

# --- CLOUDINARY CONFIG ---
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# --- FLYWAY ---
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true